---
- name: Get Mypython CR Details
  k8s_info:
    api_version: v1beta1
    kind: Mypython
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: mypython_resources
 
- name: Set Mypython CR status
  k8s_status:
    api_version: v1beta1
    kind: Mypython
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      phase: "{{ pending }}"
  when: (mypython_resources.resources[0].status.phase is not defined)
- name: deploy calci frontend
  vars:
    frontend:
      image: "{{  lookup('env', 'RELATED_IMAGE_FRONTEND') }}"
  k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: flaskcalculator
        namespace: "{{ ansible_operator_meta.namespace }}"
        labels:
          app: flaskcalculator
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: flaskcalculator
        template:
          metadata:
            labels:
              app: flaskcalculator  
          spec:
            serviceAccount: my-python-app
            containers:
            - name: flaskcalculator
              image: "{{ frontend.image }}"
              imagePullPolicy: Always
              ports:
              - name: flaskcalculator
                containerPort: 5000
              securityContext: {}
          serviceAccountName: my-python-app
          serviceAccount: my-python-app
        strategy:
          type: Recreate
- name: create service for flaskcalculator
  k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata: 
        name: flaskservice
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels:
          app: flaskcalculator
      spec:
        selector:
          app: flaskcalculator
        ports:
          - protocol: TCP
            port: 5000
            targetPort: 5000
- name: create route for flaskcalculator
  k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: flaskroute
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels:
          app: flaskcalculator
      spec:
        path: /
        to:
          kind: Service
          name: flaskservice
        port:
          targetPort: 5000
          
name: Set CR Status to Complete
  k8s_status:
    api_version: v1beta1
    kind: Mypython
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      phase: "{{ completed }}"
